# How Prepared is your City for a Natural Disaster? {#Prepared?}



Natural Disasters
As we have recently seen in the United States, natural disasters can cause loss of life and immense infrastructure damage. If a natural disaster were to happen in your city, how well prepared is the local government to mitigate for this? How long would it take to evacuate the danger zone? This study would evaluate how prepared a City and its citizens are for a natural disasters, and provide tools to utilities, first responders, and government agencies to improve reaction to natural disasters.
Criteria
Natural disasters require both citizen and government cooperation to reduce loss of life and damage to infrastructure. Although natural disasters are notoriously difficult to predict, there may be methods that can assist with either prediction of natural disasters or increasing response time once a disaster has been correctly identified. These steps would have to be region specific, but this pilot study will focus on the City of Los Angeles.
Prediction Improvement
Improving the ability to predict natural disasters is the first line of defense for a city's preparation. The expansion of monitoring equipment will be the primary information source for this model. Monitoring equipment would include: 1) seismic monitoring equipment along fault lines; 2) wind and ocean monitoring for tsunami predictions; 3) temperature and humidity (lack of) gauges to predict forest fires; and 4) weather and surface water gauges to predict flash floods. Predictive analytics will utilize this data to develop models (lead by experts in climatology, geology, oceanography, hydrology, fire fighting, and engineering) to predict and track these disasters, and determine the areas that would be severely affected.
The collected data would need to be implemented in an open source cloud to allow these specialized teams the ability to communicate and collaborate. 
These models would upload their predictions to a live geographical map that would utilize all the predictions and display which regions are impacted by certain natural disasters. This predictive model and map combination will allow cities to better prepare for natural disasters by knowing which disaster will occur and which region will be affected. Along with the predictions, population, utility (water and power) data will be implemented in the map to provide both first responders and agencies responsible for water and power appropriate data to enable them to minimize loss of life, damage to infrastructure, and number of citizens without access to clean water and electricity. 
Response Improvement
First responders will be able to access the generated live maps and determine which areas will demand their attention. The population data, populated through the U.S. Census Bureau, will provide a better understanding of the number of people affected as well as the number of elderly and children that may require special assistance. The general public’s live feed through social media and a direct information gathering platform will also be helpful in deciphering response requirements. The live feed could assist in deciphering which transit routes have been impacted and determine the optimal route for first responders. 
In terms of response time for potable water and power utilities, being notified of a natural disaster prior to its occurrence can be the difference between regions without access to clean water and power and those with access. This lead time will improve resource allocation and allow field crews use other methods to transmit water and power if they know the usual operational procedure will not suffice due to damaged infrastructure. An example of this would be to change the route of electricity flow if it is known power transmission towers in a particular region have an increased risk of being damaged. This minor modification of normal operations could produce positive results and avoid any service outages. 
Limitations and Measurements
There are many considerations that are required to determine a City’s natural disaster preparation. The items listed above only account for a small percentage of critical information. This study is intended to determine Cities’ preparation efforts as well as the general public's ability to correctly react to a natural disaster. The limitation foreseen in this study is the natural disaster itself. We can not determine how severe the natural disasters can be, but preparation levels is a criteria that can be measured.
The main challenge lies with the ability to manage these large data sets, process and decipher this data, and transmit this information to the masses when cellular, power, and internet may all be out of service. 
